[tool.poetry]
name = "minerva"
version = "0.1.0"
description = "GPT-powered bot built to help students learn software development"
authors = ["Yurij Mikhalevich <yurij@mikhalevi.ch>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^0.27.8"
discord = "^2.2.2"
python-dotenv = "^1.0.0"
tiktoken = "^0.3.3"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
pytest = "^7.3.1"
flake8 = "^6.0.0"

[tool.poetry.scripts]
minerva = "minerva.app:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
