name: Deploy

on:
  push:
    # branches:
    #   - main

concurrency: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy
        env:
          DEPLOY_HOST: '${{ secrets.DEPLOY_HOST }}'
          DISCORD_TOKEN: '${{ secrets.DISCORD_TOKEN }}'
          GUILD_ID: '${{ secrets.GUILD_ID }}'
          OPENAI_API_KEY: '${{ secrets.OPENAI_API_KEY }}'
        run: |
          echo "${DEPLOY_HOST} ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFPPx332w7K1L4b9p6o9957VBOq414gpQ26dh1KVCZr+DtarsjksqDyK0pW9ukF/k9YyAnz2PsrkVCJbFNyxd70=" >> ~/.ssh/known_hosts
          docker context create --docker "host=ssh://root@${DEPLOY_HOST}" --description "deploy server" "mfabt.club"
          echo "DISCORD_TOKEN=${DISCORD_TOKEN}" > .env
          echo "GUILD_ID=${GUILD_ID}" >> .env
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> .env
          docker --context "mfabt.club" compose up --build -d
